openstack-k8s-operators/tcib

- AUTHORS
- roles/modify_container_image/defaults/main.yml
- roles/modify_container_image/files/dev_install.sh
- roles/modify_container_image/files/rpm_install.sh
- roles/modify_container_image/files/yum_install.sh
- roles/modify_container_image/meta/main.yml
- roles/modify_container_image/tasks/copy_rpms.yml
- roles/modify_container_image/tasks/dev_install.yml
- roles/modify_container_image/tasks/get_original_user.yml
- roles/modify_container_image/tasks/main.yml
- roles/modify_container_image/tasks/modify_image.yml
- roles/modify_container_image/tasks/precheck.yml
- roles/modify_container_image/tasks/rpm_install.yml
- roles/modify_container_image/tasks/yum_common.yml
- roles/modify_container_image/tasks/yum_install.yml
- roles/modify_container_image/tasks/yum_install_buildah.yml
- roles/modify_container_image/tasks/yum_update.yml
- roles/modify_container_image/tasks/yum_update_buildah.yml
- roles/modify_container_image/templates/Dockerfile-dev.j2
- roles/modify_container_image/templates/Dockerfile-rpm.j2
- roles/modify_container_image/templates/Dockerfile-yum-install.j2
- roles/modify_container_image/templates/Dockerfile-yum.j2
- roles/modify_container_image/templates/yum_update.sh.j2
- tcib/client/container_image.py
It will be used with openstack tcib container image hotfix command.
Signed-off-by: Chandan Kumar <raukadah@gmail.com>
> Import modify image role in tcib

- container-images/tcib/base/os/cinder-base/cinder-scheduler/cinder-scheduler.yaml
- container-images/tcib/base/os/manila-base/manila-scheduler/manila-scheduler.yaml
- container-images/tcib/base/os/neutron-base/neutron-agent-base/neutron-dhcp-agent/neutron-dhcp-agent.yaml
tcib_actions should be a list.
> Fix invalid tcib_actions

- container-images/tcib/base/os/tempest/tempest.yaml
This fixes the path directory for
the tempest container build.
> Fix typo in tempest container files

- ci/playbooks/build_zed_containers.yaml
- ci/roles/build_containers/defaults/main.yaml
- ci/roles/build_containers/tasks/main.yaml
- ci/roles/build_containers/vars/main.yaml
Improvements to containers_build role
- Improve default role vars 
- Added separate task to tag and push containers using buildah
- Added missing exclude containers for master
Signed-off-by: Chandan Kumar <raukadah@gmail.com>
> Improvements to container_builds role

- AUTHORS
- README.rst
It contains steps to build a single container.
> Add steps to build openstack services containers

- container-images/tcib/base/base.yaml
- container-images/tcib/base/collectd/collectd.yaml
- container-images/tcib/base/mariadb/mariadb.yaml
- container-images/tcib/base/os/horizon/horizon.yaml
- container-images/tcib/base/os/keystone/keystone.yaml
- container-images/tcib/base/os/nova-base/nova-compute/nova-compute.yaml
- container-images/tcib/base/os/nova-base/nova-libvirt/nova-libvirt.yaml
... because now only CentOS 9 and RHEL 9 are supported.
> Clean up logics for CentOS/RHEL 8

- container-images/tcib/base/openstackclient/openstackclient.yaml
- Better set up cloud-admin user in openstackclient
- Add iputils to openstackclient
- Add missing baremetal command completion
> openstackclient improvements

- container-images/kolla/base/set_configs.py
- container-images/kolla/base/sudoers
Copied from kolla fix[1].
[1] https://review.opendev.org/c/openstack/kolla/+/856032
> Fix CVE-2022-38060

- container-images/tcib/base/base.yaml
- container-images/tcib/base/multipathd/multipathd.yaml
- container-images/tcib/base/os/cinder-base/cinder-volume/cinder-volume.yaml
- container-images/tcib/base/os/glance-api/glance-api.yaml
- container-images/tcib/base/os/horizon/horizon.yaml
- container-images/tcib/base/os/os.yaml
... to reduce the size of the base image as well as the all images inheriting the base.
> Remove a few more unnecessary packages from the base image

- OWNERS
I may no longer be able to contribute to this project.
> Remove myself from owner

- container-images/containers.yaml
- container-images/kolla/base/uid_gid_manage.sh
- container-images/tcib/base/os/tobiko/run_tobiko.sh
- container-images/tcib/base/os/tobiko/tobiko.yaml
- container-images/tcib/base/os/tobiko/tobiko_sudoers
This PR adds the files needed to create a tobiko container image.
Co-Authored-By: Omer Schwartz
> Adding tobiko image

- container-images/tcib/base/os/tempest/tempest-extras/tempest-extras.yaml
This is not tempest plugin, but allows to
run existing test cases with high concurrency.
> tempest-stress to tempest-extras

- container-images/tcib/base/ovn-bgp-agent/ovn_bgp_agent.yaml
> This is required to connect to NB/SB db addresses that use DNS names.

- container-images/tcib/base/os/tempest/run_tempest.sh
This reverts commit 13395552bbc8821702f931769ab83fe462d473c5, reversing changes made to 66943106e27b63304ccca3e9ec11b0ce9f376bb8.
> Revert "Merge pull request #96 from lpiwowar/feature/tempest-parameter"

- container-images/tcib/base/os/tempest/tempest-extras/tempest-extras.yaml
Add the Manila tempest plugin [1] to the tempest container.
[1] https://opendev.org/openstack/manila-tempest-plugin
> Add Manila Plugin to tempest extras

- container-images/tcib/base/os/nova-base/nova-compute/nova-compute.yaml
Pinning only for centos stream
> pin libvirt-libs due to RHEL-20609

- container-images/tcib/base/os/tobiko/run_tobiko.sh
[OSPRH-4828](https://issues.redhat.com//browse/OSPRH-4828)
> [Tobiko] Install openshift client

- container-images/tcib/base/os/tempest/run_tempest.sh
This patch adds the option to specify an extra image for tests that require advanced images. This change is specific for Whitebox Neutron Tempest plugin as it is not certain, if general solution is needed. It would be also ineffective to achieve generalisation due to different methods of notation. So for now, the solution is done for Whitebox Neutron Tempest plugin only.
> Add option to add extra image

- container-images/tcib/base/os/tempest/run_tempest.sh
The TEMPEST_NEUTRON_IMAGE_* variables were tailored specifically to the
neutron-tempest-plugin. Those variables did not allow to specify things
like flavor, ID or name of the image that should be uploaded to
OpenStack.
This patch introduces a new set of variables called
TEMPEST_EXTRA_IMAGES_* that can be used to specify a list of images
that should be uploaded to OpenStack. These variables accepted
a comma-separated list of values.
> [Tempest] Make TEMPEST_NEUTRON_IMAGE more generic 

- container-images/tcib/base/os/tempest/run_tempest.sh
With the merge of this PR we officially remove the support for neutronExtraImage parameter [1]. We can safely remove the parameter now.
[1] https://github.com/openstack-k8s-operators/ci-framework/pull/1790
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1790
> [tempest] Remove TEMPEST_NEUTRON_EXTRA_IMAGE

- zuul.d/job.yaml
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1885
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1884
> Move tcib jobs to update_containers role

- container-images/containers.yaml
Accidentally removed horisontests from container list re-adding
> re-add horizontests

- container-images/tcib/base/os/tempest/run_tempest.sh
We encountered Tempest failures due to the image being in the importing process.
This patch ensures the image is active when the Tempest tests are executed.
Jira: https://issues.redhat.com/browse/OSPRH-9284
> Wait for image to be active after creation

- container-images/tcib/base/netutils/netutils.yaml
Jira: [OSPRH-10551](https://issues.redhat.com//browse/OSPRH-10551)
> Container image for octavia and designate predictable IPs support

- container-images/tcib/base/os/horizontest/run_horizontest.sh
Add required test variables/values which are used as default values for Horizon tests, into horizon.conf
> Add required test variables into horizon.conf

- zuul.d/job.yaml
Fixes https://issues.redhat.com/browse/OSPCIX-634
> Changing cifmw_test_operator_index to 18.0-fr1-latest tag

- zuul.d/job.yaml
The jobs are broken and we probably should not run those tests here.
> Drop tobiko tests from the jobs

- container-images/tcib/base/os/horizontest/run_horizontest.sh
This PR adds new variables to the horizontest image that can be set by test_operator
> Add extra variables to horizontest image

- container-images/tcib/base/tobiko/tobiko.yaml
[OSPCIX-716](https://issues.redhat.com//browse/OSPCIX-716)
> [tobiko] Upgrade pip before installing tobiko requirements

- container-images/containers.yaml
- container-images/kolla/base/uid_gid_manage.sh
- container-images/tcib/base/os/cloudkitty-base/cloudkitty-api/cloudkitty-api.yaml
- container-images/tcib/base/os/cloudkitty-base/cloudkitty-base.yaml
- container-images/tcib/base/os/cloudkitty-base/cloudkitty-processor/cloudkitty-processor.yaml
- container-images/tcib/base/os/horizon/horizon.yaml
This reverts commit fe3d78c2f5b45833ca27a59674d2103002edac7e.
> Revert "Added CloudKitty to tcib to produce api and processor images"

- container-images/tcib/base/os/horizontest/run_horizontest.sh
Fix for /OSPCIX-959
Try to clone in loop with delay between tries.
In case of exceeded retries, exit script.
Co-Authored-By: Szymon Datko <sdatko@redhat.com>
> Add retry clone and graceful fail /OSPCIX-959
