container-images/tcib/base/os/heat-base/heat-all/heat-all.yaml, container-images/tripleo_containers.yaml
This was used in standalone deployment process of TripleO.
=> Remove heat-all container

tcib-dev-env.rc, tcib/client/container_image.py
This copies the tripleo-ansible/ansible-test-env.rc approach of allowing image definition files to come from the local git checkout instead of an installed location.
=> Add a dev mode source file for local development

ci/roles/build_containers/defaults/main.yaml, ci/roles/build_containers/templates/build_containers.sh.j2
The following changes were needed to get
container build jobs to pass:
- use openstack tcib container build command
=> Update ci roles to work with build jobs

container-images/tcib/base/openstackclient/openstackclient.yaml
This ensures we install more client libraries so that we can use subcommands for all services supported by oko.
Note this change does not cover legacy clients because these do not work with clouds.yaml .
=> Install additional clients

container-images/tcib/base/base.yaml, container-images/tcib/base/haproxy/haproxy.yaml, container-images/tcib/base/mariadb/mariadb.yaml, container-images/tcib/base/os/cinder-base/cinder-backup/cinder-backup.yaml, container-images/tcib/base/os/cinder-base/cinder-volume/cinder-volume.yaml, container-images/tcib/base/os/manila-base/manila-share/manila-share.yaml, container-images/tcib/base/ovn-base/ovn-northd/ovn-northd.yaml, container-images/tcib/base/rabbitmq/rabbitmq.yaml, container-images/tcib/base/redis/redis.yaml
We will not use pacemaker in oko deployment because operator should take care of clustering/HA.
Also socat is no longer used so this PR also removes it.
=> Remove unused pacemaker packages

container-images/tcib/base/openstackclient/openstackclient.yaml
python3-ironicclient is needed on this
container build.
=> Fix typo on package install - openstackclient.yaml

container-images/tcib/base/base.yaml
python-tcib package is now available in podified component repo[1]. python-tcib-containers contains all the required container-images for tcib.
python-tcib-containers replaces the tcib package in this pr.
[1]. https://trunk.rdoproject.org/centos9-master/component/podified/current/
=> Add python-tcib-containers package

requirements.txt, test-requirements.txt
Some of the requirements are not really used and can be removed.
=> Remove unused requirements

test-requirements.txt
This was actually used and should have not been removed.
=> Restore requests-mock

ci/roles/build_containers/vars/main.yaml
Antelope container builds are required
and vars need to be added.
=> Add antelope excludes

ci/roles/build_containers/vars/main.yaml
This PR adds the osp18 exclude_containers
option and switches to use anchors to avoid
duplication.
=> Add exclude_containers option for osp18

ci/roles/build_containers/vars/main.yaml
We have already removed neutorn-mlnx-agent so we don't need to exclude it.
=> Remove redundant exclude_containers

ci/roles/build_containers/vars/main.yaml
Update the excludes list to keep to this
convention.
=> tcib uses rhel as the distro for Red Hat distros

container-images/tcib/base/os/aodh-base/aodh-api/aodh-api.yaml, container-images/tcib/base/os/gnocchi-base/gnocchi-base.yaml
Aodh and Gnocchi do not require this library, really.
=> Remove unused python3-ldappool

container-images/tcib/base/os/ironic-base/ironic-pxe/ironic-pxe.yaml
The ironic-pxe container requires ss command to check status of UDP port used by dnsmasq.
=> Fix missing ss command in ironic-pxe container

ci/roles/build_containers/vars/main.yaml
For downstream builds, the usual reference is
'rhos' rather than 'osp'.
=> Rename openstack-release to use 'rhos'

ci/roles/build_containers/defaults/main.yaml, tcib/builder/buildah.py, tcib/client/container_image.py, tcib/tests/test_buildah.py
This will allow the original build tag to be discovered by inspecting a stable tag such as current-podified. This may become useful later to replace stable tags with versioned tags for minor updates of running services.
=> Set label tcib_build_tag to match tag

container-images/tcib/base/base.yaml
install scripts to make it available to be build by other build systems like ocds/brew where a job cannot pre-install the package
=> Install python-tcib-containers package before it tries to

AUTHORS, container-images/tcib/base/os/tempest/run_tempest.sh, container-images/tcib/base/os/tempest/tempest.yaml
Updating tempest container to run tempestconf and tempest, and export the results.
Initially, this container just install the required packages to run tempest, with this patch, it will also add the run_tempest.sh script to execute tempest automatically setting the tcib_entrypoint. This will make it easier to move forward with tempest running on edpm jobs.
=> Updating tempest container

container-images/tcib/base/mariadb/mariadb.yaml
When galera is used with TLS, the SST method (rsync or mariabackup) requires encryption. This is currently achieved via a socat tunnel, so add socat as a dependency in the mariadb image.
=> Require socat in mariadb image

container-images/tcib/base/openstackclient/openstackclient.yaml
This ensures we install glanceclient library so that we can use additional commands for glance service which are not supported/available in openstackclient.
=> Install glanceclient

roles/modify_container_image/tasks/yum_update_buildah.yml, roles/modify_container_image/templates/yum_update.sh.j2, setup.cfg, tcib/client/container_image.py, tcib/client/utils.py
In some situtations it's desireable to update all RPMs in container that are from a specific repo.  This PR updates and exposes existing ansible tasks to do just that.
=> Add tool to expose yum_update ansible tasks

AUTHORS, tcib/client/container_image.py
https://github.com/openstack-k8s-operators/tcib/pull/56 allows source container-images from the build host, not an rpm.
The above patch adds a new variable tcib_variables[1] to store image_config dict update value[2] and move it out of loop[3].
The value stored in tcib_variables is not getting updated when it is used in loop leading to following error[4]
```
Error: cannot find Containerfile or Dockerfile in context directory"
```
This patch drops the tcib variables and moves the dict back to its place.
[1.] https://github.com/openstack-k8s-operators/tcib/pull/56/files#diff-11a2750a37ee46b0df221580918b8e61e0154531984bb2d0eb077c8f5b4a4834R571 [2.] https://github.com/openstack-k8s-operators/tcib/pull/56/files#diff-11a2750a37ee46b0df221580918b8e61e0154531984bb2d0eb077c8f5b4a4834L594 [3.] …
=> Drop tcib_variables in favor of image_config

container-images/tcib/base/os/tempest/run_tempest.sh
Tempestconf allow user to pass a yaml file containing options to be overriden in tempest.conf file. This patch add this option, checking if the file profile.yaml exists, if so, it pass the --profile, otherwise, it maintain the default behavior.
=> Add option to parse a profile to tempestconf

container-images/tcib/base/os/ironic-base/ironic-conductor/ironic-conductor.yaml
Ironic no longer use this library and replaced it by openstacksdk[1].
[1] https://review.opendev.org/c/openstack/ironic/+/669855
=> Ironic: remove unused ironic-inspector-client

container-images/tcib/base/mariadb/mariadb.yaml
SST transfers can be encrypted with socat when the transfer method is mariabackup or rsync_tunnel. Starting mariadb 10.5, the later can be replaced by the rsync transfer method, which gain support for encrypted SST via stunnel.
Add stunnel in the mariadb image to be able to deprecate rsync_tunnel, which was implemented before rsync supported encryption.
=> Require stunnel in mariadb image

container-images/kolla/base/set_configs.py, container-images/kolla/base/sudoers
https://github.com/openstack-k8s-operators/tcib/pull/62 caused failures: 
https://logserver.rdoproject.org/20/39420/42/check/periodic-podified-edpm-deployment-antelope-ocp-crc-1cs9/2e359a3/ci-framework-data/logs/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-44315d98038be6ade762a669a25e052c0fdd39d886d22900bfc1944a2eb0a9e3/namespaces/openstack/pods/ovsdbserver-nb-0/ovsdbserver-nb-0-describe.log
~~~
ERROR:__main__:Unexpected error:
Traceback (most recent call last):
File "/usr/local/bin/kolla_set_configs", line 403, in main
config = load_config()
File "/usr/local/bin/kolla_set_configs", line 286, in load_config
config = load_from_file()
File "/usr/local/bin/kolla_set_configs", line 276, in load_from_file
with open(config_file) as f:
FileNotFoundError: [Errno 2] No such file or …
=> Revert "Fix CVE-2022-38060"

container-images/tcib/base/os/glance-api/glance-api.yaml, container-images/tcib/base/os/nova-base/nova-compute/nova-compute.yaml
The vmwareapi virt driver was deprecated a while ago[1] because of lack of CI and maintainers. Because we haven't seen any users attempting to use the driver even in TripleO project, let's remove the package to reduce image size.
[1] https://review.opendev.org/c/openstack/nova/+/863911
=> Remove oslo.vmware from nova/glance

container-images/tcib/base/os/ceilometer-base/ceilometer-base.yaml
Ceilometer no longer uses oslo.db, since it offloaded its metric storage and event storage.
Also explicit install of tooz library is not required because the package is part of dependencies and should be installed automatically.
=> Ceilometer: Remove unused oslo.db

container-images/tcib/base/os/ceilometer-base/ceilometer-notification/ceilometer-notification.yaml
This package was required to use amqp1 backend which is being deprecated[1].
Usage of amqp1 was required by current architecture of STF. However the architecture will be updated so that we no longer use qpid dispatch router(aka QDR). So this requirement will be no longer valid in operator deployment.
[1] https://review.opendev.org/c/openstack/oslo.messaging/+/861070
=> Ceilometer: Remove python3-pyngus

container-images/tcib/base/os/gnocchi-base/gnocchi-api/gnocchi-api.yaml, container-images/tcib/base/os/gnocchi-base/gnocchi-base.yaml
apache is required only by the api container and is not used by the other containers such as metricd.
=> Gnocchi: Install apache in api container only

container-images/tcib/base/os/tempest/run_tempest.sh
The profile.yaml test is missing a space, which is throwing an error and not setting the proper profile arguments.
=> Minor fix on run_tempest.sh for tempest container

container-images/kolla/base/set_configs.py, container-images/kolla/base/sudoers
This reverts commit a741fcd4f1ac0ac1d9ad2ebef2636fa7cd8e4ed6.
Reason for revert:
The original change was reverted because of remaining usage of KOLLA_CONFIG_FILE but the environment is no longer used.
=> Revert "Revert "Fix CVE-2022-38060""

container-images/tcib/base/os/tempest/run_tempest.sh
At this moment, tempest is using all cpus available, and in some test cases this leads to timeout in some resources. Adding the hability to set the proper concurrency will fix this problems.
Depends-On: https://github.com/openstack-k8s-operators/install_yamls/pull/526
=> Add concurrency support in tempest container

zuul.d/job.yaml, zuul.d/projects.yaml
Since we are getting rid off the nested EDPM jobs we are now changing tcib to use the multinode based EDPM deployment job.
=> Switch tcib to use the multinode layout

container-images/tcib/base/openstackclient/openstackclient.yaml
Adding `ceph-common` package to the `openstackclient` means that if the `OpenStack` services are configured with `Ceph` but there are issues interacting with the cluster, we can use this Pod to ease any troubleshooting session instead of using container services (e.g. `cinder-api`) to find a working `rbd` client.
If an issue occurs (e.g. there are networking issues), mostly of the Pods that are trying to init the ceph driver will be in a `CrashLoopback`, hence even though the rbd client is present, we need to ask to `patch` an existing ctlplane CR just for testing purposes.
Finally, the `ceph-common` package is already available and provided by `RDO`, hence having it here doesn't hurt.
=> Add ceph-common to openstackclient to improve troubleshooting

container-images/tcib/base/os/tempest/run_tempest.sh
The concurrency variable wasn't being set properly, as well as the check if the concurrency was set, making tempest jobs start to fail. This patch fixes it, and also set the shell to show the output of all commands, making it easier in the future to debug any failure.
=> Fix run_tempest.sh

container-images/containers.yaml, container-images/tcib/base/os/neutron-base/neutron-agent-base/neutron-ovn-agent/neutron-ovn-agent.yaml
The image will be used to setup neutron-ovn-agent on the EDPM nodes.
Related-Issue: [OSP-26191](https://issues.redhat.com//browse/OSP-26191)
=> Add neutron-ovn-agent container image

container-images/tcib/base/os/tempest/tempest.yaml
discover-tempest-config/python-tempestconf wants to execute
qemu-img conver when --convert-to-raw argumant is passed.
=> qemu-img to tempest

container-images/containers.yaml
Tobiko is failing to build right now in downstream, in order to unblock promotions, we are skipping it for now until we figure out the main reason.
CIX: [OSPCIX-100](https://issues.redhat.com//browse/OSPCIX-100)
=> Skip build tobiko image

roles/modify_container_image/tasks/copy_rpms.yml
The json_query filter raises 'Invalid plugin FQCN
(community.general.json_query): unable to locate
collection community.general'. Hence, we replace
json_query filter with map(attribute='path').
=> Fix copy_rpms.yml

README.md, container-images/containers.yaml, tcib/client/container_image.py, tcib/tests/test_container_image.py
The note[1] indicates that dependencies will be built but this
only appears to work for the first ancestor of an image.
Fix this by walking up the directory tree for a given image to
find all ancestors to include in the build.
Also record the level of each image and process in a breadth first order,
removing the hardcoded ordering for the 'base' and 'os' images.
[1] https://github.com/openstack-k8s-operators/tcib/blob/41a73ab686826c4fc2095cbe3f76b0dc2d61147f/tcib/client/container_image.py#L537-L541
=> Fix dependency handling logic

AUTHORS, zuul.d/job.yaml
https://github.com/openstack-k8s-operators/ci-framework/pull/771 adds the support for installing tcib from rpm as a default behaviour. It also adds a var cifmw_build_containers_install_from_source to install it from source.
Since here tcib code is tested from source. So we need to update the zuul job definition so that tcib will get installed from source.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/799
=> Donot Install tcib from rpm

container-images/tcib/base/os/neutron-base/neutron-base.yaml
This is required to connect to NB/SB db addresses that use DNS names. See https://github.com/openvswitch/ovs/commit/4d55a364ff60d894dce4e2e97a489d81520dc663
=> Add python3-unbound to Neutron images

container-images/tcib/base/os/placement-api/placement-api.yaml
Currently the placement user does not have a kolla generated uid and it is not in the kolla group:
```
❯ oc rsh placement-7ccc6bc7f5-cfchj
Defaulted container "placement-api" out of: placement-api, init (init)
sh-5.1# id
uid=0(root) gid=0(root) groups=0(root)
sh-5.1# cat /etc/passwd | grep placement
placement:x:997:994:OpenStack Placement:/:/bin/bash
sh-5.1# cat /etc/group | grep kolla
kolla:x:42400:
sh-5.1# 
```
This PR will make sure that during build the proper placemenet uid and group membership is used
=> Fix placement user creation

container-images/tcib/base/os/tempest/run_tempest.sh
This patch introduces tempestconf parameters for the tempest container. Currently, it is not possible to specify with what parameters should be tempest and discover-tempest-config executed.
This patch introduces a set of environment variables prefixed with TEMPESTCONF_  that can be used to tell the container which arguments should be used when executing discover-tempest-config.
=> Add support for tempestconf parameters

container-images/tcib/base/os/octavia-base/octavia-api/octavia-api.yaml
This will be required to connect to the NB/SB db addresses using DNS names.
=> Add python3-unbound to the Octavia API image

container-images/tcib/base/os/tempest/run_tempest.sh
This patch introduces tempest parameters for the tempest container. Currently, it is not possible to specify with what parameters should be tempest executed.
This patch introduces a set of environment variables prefixed with TEMPEST_ that can be used to tell the container which arguments should be used when executing tempest.
=> Add tempest parameters for the tempest container

container-images/containers.yaml, container-images/tcib/base/os/tempest/tempest-all/tempest-all.yaml
Tempest image should contain only tempest while tempest-all image
should contain tempest with all relevant plugins.
Depends-On: https://github.com/openstack-k8s-operators/tcib/pull/97
=> Define tempest-all image

container-images/tcib/base/os/tempest/tempest-all/tempest-all.yaml
The package tempest-whitebox is not yet available on rhel, skipping it for now until we get a proper rpm being built.
=> Temporarly skip openstack-tempest-all

container-images/tcib/base/os/tempest/tempest-all/tempest-all.yaml
openstack-tempest-all package was temporarily replaced with only
openstack-tempest one because whitebox-neutron-tempest plugin
wasn't available on rhel.
These patches make sure that the plugin is included in the
openstack-tempest-all package only in upstream:
https://review.rdoproject.org/r/q/I93f6cee77927dfadd15c8093b49b1ed1f3e04cdc
Thus it's safe to get the things back as they were.
=> Remove temporary skip of tempest-all package

container-images/tcib/base/os/placement-api/placement-api.yaml
The openstack-placement-api rpm provides an example placement httpd config at /etc/httpd/conf.d/00-placement-api.conf when enable httpd to read configs from /etc/httpd/conf.d to fail.
```
$ podman run -it -u root --rm quay.io/podified-antelope-centos9/openstack-placement-api:current-podified sh sh-5.1# rpm -qf /etc/httpd/conf.d/
00-placement-api.conf  autoindex.conf         README                 ssl.conf               userdir.conf           welcome.conf
sh-5.1# rpm -qf /etc/httpd/conf.d/00-placement-api.conf
openstack-placement-api-9.0.1-0.20230331173037.b3652fe.el9.noarch
```
This deletes this default config as the operator will provide a httpd config for placement.
=> [placement] remove example httpd /etc/httpd/conf.d/00-placement-api.conf

container-images/tcib/base/os/tempest/tempest-extras/tempest-extras.yaml
The whitebox tempest plugin actually depends on the barbican tempest plugin otherwise the vTPM tests are failing with
```
cls.os_primary.secrets_client = service_clients.secret_v1.SecretClient(
AttributeError: 'ServiceClients' object has no attribute 'secret_v1'
```
So this patch adding it.
Implements: https://issues.redhat.com/browse/OSPRH-2451
=> [tempest-extras]Add barbican tempest plugin

container-images/tcib/base/os/tobiko/run_tobiko.sh, container-images/tcib/base/os/tobiko/tobiko.yaml
In order to make the Tobiko tcib image more configurable, this patch adds some environment variables that will be relevant for:
- the generated tobiko.conf file
- some variables that will be relevant for tox and pytest, modifying the test execution
=> Adding some env variables to Tobiko image

zuul.d/job.yaml
This change guarantee that job running in this repo are also testing tempest images built in the content-provider job.
=> Run tempest images built in content-provider job

container-images/tcib/base/openstackclient/openstackclient.yaml, container-images/tcib/base/os/os.yaml
This patch adds python3-observabilityclient dependency to OpenStack images. The package is new Aodh dependency.
=> Install observabilityclient

container-images/tcib/base/openstackclient/openstackclient.yaml
Add the aodhclient to enable the `openstack alarm` commands.
=> Add python3-aodhclient

container-images/tcib/base/os/cinder-base/cinder-volume/cinder-volume.yaml
Cinderlib is being deprecated [1], so we should stop including it in the cinder-volume container.
[1]: https://review.opendev.org/q/topic:%22deprecate-cinderlib%22
=> Remove deprecated cinderlib from cinder volume

container-images/tcib/base/os/tobiko/run_tobiko.sh, container-images/tcib/base/os/tobiko/tobiko.yaml
The tobiko.conf file will be generated by ci-framework, which will be more flexible than creating it with crudini commands on the run_tobiko.sh script.
Another improvement is to obtain ssh key files generated by ci-framwork too. Those files can be shared between different tobiko containers running tests, so that they can connect to the VMs created by a previous tobiko container (the Openstack workloads created by tobiko are persistent).
Related: https://github.com/openstack-k8s-operators/ci-framework/pull/1044
=> [Tobiko] Get tobiko.conf and ssh keys from external_files dir

container-images/tcib/base/openstackclient/openstackclient.yaml, container-images/tcib/base/os/os.yaml
This package is not yet available as rpm, and it is blocking our promotion pipeline. It should be re-added once the package is ready.
=> Remove python3-observabilityclient

container-images/tcib/base/os/ironic-base/ironic-inspector/ironic-inspector.yaml
To be able to terminate TLS using httpd.
Jira: [OSPRH-4220](https://issues.redhat.com//browse/OSPRH-4220)
=> [ironic] Add httpd/mod_ssl to ironic-inspector image

container-images/tcib/base/openstackclient/openstackclient.yaml, container-images/tcib/base/os/os.yaml
We do have now a build in downstream, so we can enable it again
=> Re-add python3-observabilityclient

container-images/kolla/base/httpd_setup.sh
Kolla is generating a self-signed cert on container startup which we do not use. This will burn considerable resources and time for every container start.
If we have mounted a custom ssl.conf skip the step.
=> Skip unnecessary TLS cert creation on container startup

container-images/tcib/base/os/tempest/run_tempest.sh
Use upper-constraints that match the version of tempest being run. This avoids incompatabilities caused by pip installing the latest versions of the dependencies.
=> [tempest] Install external plugins using upper-constraints

container-images/tcib/base/os/tempest/run_tempest.sh
If there is a new line at the end of either TEMPESTCONF_REMOVE or TEMPESTCONF_APPEND then it might happen that the run_tempest.sh adds --remove/--append parameter to the tempest command with an empty value.
For example:
TEMPESTCONF_REMOVE="section.subsection False
" # <-- New line
leads to:
tempest run --remove section.subsection False --remove
Also, both --remove and --append expect '=' between section name and
value [1].
=> [tempest] Fix parsing of TEMPESTCONF_{REMOVE,APPEND}

container-images/tcib/base/os/tobiko/run_tobiko.sh, container-images/tcib/base/os/tobiko/tobiko.yaml
Some tobiko tests capture traffic on the tobiko container where tests are executed using tcpdump.
For that reason:
- tcpdump needs to be added to the list of packages that need to be installed on the tobiko image.
- the container will need to be executed with root permissions, so the run_tobiko.sh script needs to manage properly the mounted files and directories.
=> [Tobiko] Add tcpdump and prepare to run containers as root

container-images/tcib/base/os/nova-base/nova-compute/nova-compute.yaml
libvirt 10 landed on CentOS stream so this downgrade is no longer required.
=> Removing libvirt downgrade

container-images/tcib/base/os/tempest/run_tempest.sh, container-images/tcib/base/os/tempest/tempest-all/tempest-all.yaml
python3-octavia-tempest-plugin rpm builds the go test server during the
installation [1]. This patch ensures that the tempest-all image by
default sets the path to the test server binary in tempest.conf in case
it is needed by octavia-tempest-plugin.
[1] https://github.com/rdo-packages/octavia-tempest-plugin-distgit/blob/rpm-master/python-octavia-tests-tempest.spec#L127
=> [Tempest-all] Configure path to octavia test server 

container-images/tcib/base/os/tobiko/run_tobiko.sh
The test-operator requires the ability to specify arbitrary mount point
for the ssh keys. This patch introduces a new env variable called
TOBIKO_KEYS_FOLDER that contains a path to a folder containing
keys with ${TOBIKO_PRIVATE_KEY_FILE}* name.
=> Enable mounting of ssh keys to arbitrary folder

container-images/tcib/base/openstackclient/openstackclient.yaml
Install packange python3-ironic-inspector-client in openstackclient container.
=> openstackclient: python3-ironic-inspector-client

container-images/tcib/base/os/ironic-base/ironic-inspector/ironic-inspector.yaml
The ss command is used in the probe.
```
5m57s  Warning  Unhealthy  pod/ironic-inspector-0   Readiness probe failed: sh: line 1: ss: command not found
```
=> Install iproute in ironic-inspector container

container-images/tcib/base/os/ironic-base/ironic-conductor/ironic-conductor.yaml
During Caracal release, ironic, proliantutils and scciclient have moved to pysnmp-lextudio fork to replace the unmaintained pysnmp.
In order to make this container file compatible with both antelope and master, we can symply remove pysnmp from the explicit list of packages and simply let proliantutils and scciclient to pull the right package for each release.
=> Remove pysnmp from explicit list of packages in ironic-conductor

container-images/tcib/base/tobiko/run_tobiko.sh
This change introduces TOBIKO_LOGS_DIR_NAME variable for the tobiko
image. This variable enables to specify directory name that should
contain the collected logs.
=> [Tobiko] Add support for separate log dirs

container-images/tcib/base/tobiko/tobiko.yaml, zuul.d/job.yaml
Before this patch, tox version >=4.13 was installed using pip, but that caused some incompatibility issues with dependencies that were installed via RPM (pip could not update versions).
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1254
=> [Tobiko] Pin tox to 4.13

container-images/tcib/base/tobiko/run_tobiko.sh
Currently we look for the logs based on the name of testenv but we do not take into account the fact that the testenv can have the following format:
'functional -- tobiko/tests/functional/podified/test_topology.py'
This patch ensures that we take only the first part of the testenv name ('functional') into account when copying the logs.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1254
=> [Tobiko] Fix extraction of log dir name

container-images/tcib/base/os/ironic-base/ironic-conductor/ironic-conductor.yaml
https://issues.redhat.com/browse/OSPRH-5427 drops the openstack-ironic-staging-drivers from OSP-18 and package is removed from downstream dlrn builds, leading to failure in building ironic conductor container image.
Dropping this package from tcib fixes the issue.
=> Drop openstack-ironic-staging-drivers from ironic-condutor

container-images/tcib/base/os/ironic-base/ironic-conductor/ironic-conductor.yaml
The syslinux-nonlinux package is now recommended and not required.
See https://review.rdoproject.org/r/c/openstack/ironic-distgit/+/51902
=> Install syslinux-nonlinux in ironic explicitly

container-images/tcib/base/os/tempest/run_tempest.sh
Tempest workflows are introduced together with this change in the test-operator [1]. This change adds a variable that can be used to specify name of a directory where logs for a specific workflow step are stored.
[1] https://github.com/openstack-k8s-operators/test-operator/pull/67
=> [Tempest] Introduce workflow dir

container-images/tcib/base/os/tempest/run_tempest.sh
It seems that there is no direct way how to set 600 for a mounted secret using openshift. This patch creates a workoround that copies the mounted secret (private key) to the correct destination and sets the correct permissions for it.
=> Fix private key permission

container-images/tcib/base/os/tempest/run_tempest.sh
We do not add a space at the end of the test_server_patch tempestconf override option. This breaks the discover-tempest-config generation when TEMPEST_NEUTRON_IMAGE_URL is set.
=> Add space to test_server_patch octavia override section

container-images/tcib/base/tobiko/run_tobiko.sh, container-images/tcib/base/tobiko/tobiko.yaml
The tobiko repo, the openshift client (oc) and the ubuntu image
were downloaded when the tobiko container started running, before this
patch.
After this patch, those operations will be performed during the image
creation, so when the container starts running tobiko, oc and ubuntu
image will already be available.
[OSPRH-6347](https://issues.redhat.com//browse/OSPRH-6347)
=> [Tobiko] Download tobiko repo, oc and ubuntu image during image creation

container-images/tcib/base/os/tempest/run_tempest.sh
Currently, the run_tempest.sh creates the advanced image without --public. This can cause failures as users created by tempest can not discover the created image.
=> Fix advanced image creation

container-images/tcib/base/os/tempest/run_tempest.sh
We do not need to re download the image on tempest rerun if image already created.
=> Download advanced image only if glance image don't exist

container-images/tcib/base/os/glance-api/glance-api.yaml
This dependency is required for users trying to use the s3 backend.
=> glance-api: install python3-boto3 as to support s3

container-images/tcib/base/os/tempest/run_tempest.sh
This patch introduces an option for test-operator that keeps the pod running even after a failure occured or after the file run_tempest.sh has reached its end (sleep infinity). It resolves the issue that oc rsh session is killed once the execution of the run_tempest.sh finishes.
=> Add debug mode for test-operator

container-images/tcib/base/os/tempest/run_tempest.sh
TEMPEST_PARALLEL variable should not have a default value set. Tempest has a default value, setting another default value in, basically, a wrapper introduces unnecessary edge cases, e.g. if someone sets TEMPEST_SERIAL and doesn't notice that TEMPEST_PARALLEL has a default value, it will result in setting both (--serial and --parallel) and Tempest will fail on that.
=> [tempest] TEMPEST_PARALLEL shouldn't have default

container-images/tcib/base/os/tempest/run_tempest.sh
Tempest run requires a tempest.conf, without it, it does not make sense to run Tempest. If discover-tempest-config fails for any reason, we should not run tempest to save execution time.
=> Don't run Tempest if discover failed

container-images/tcib/base/os/horizontest/run_horizontest.sh
Currently we had the code to create group as part of our downstream code but upstream code doesn't have it as devstack deployment has group resource created as part of deployment .
In order to keep the code similar to what we have in upstream , we are moving group resource creation part to horizon test image .
[OSPRH-7938](https://issues.redhat.com//browse/OSPRH-7938)
=> Add create group option in horizontest image

zuul.d/job.yaml, zuul.d/projects.yaml
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1892
=> Use Meta content provider in tcib

container-images/tcib/base/tobiko/tobiko.yaml
After the owner of the tobiko home directory (/var/lib/tobiko) was set, some other actions like creating a subdir were done using the root user.
This patch moves the action that sets the owner of that directory and its subdirectories to the end of the list of actions.
=> Move setting tobiko dir owner to the last action

container-images/containers.yaml, container-images/kolla/base/uid_gid_manage.sh, container-images/tcib/base/ansible-tests/ansibleTests.yaml, container-images/tcib/base/ansible-tests/ansible_sudoers, container-images/tcib/base/ansible-tests/run_ansible.sh
Create container to run ansible playbooks from. This container is meant to be used for NFV performance test runs using test operator
=> Create container to run ansible playbooks from

container-images/tcib/base/os/glance-api/glance-api.yaml
As done for `Cinder`, we add the `ceph-common` package to `glanceAPI` to make the troubleshooting against the `Ceph` cluster easier. `Glance` is attached to the `storage` network and usually it already has the required `ceph` config.
Jira: https://issues.redhat.com/browse/OSPRH-839
=> Add ceph-common to Glance container

container-images/tcib/base/os/horizontest/run_horizontest.sh
Add required variables/values for horizon.conf which is used as a source of default values for Horizon integration tests.
=> Add required variables for horizon.conf

container-images/tcib/base/os/horizontest/run_horizontest.sh
We need to make sure Horizontest pod exits correctly , based on the exit value the pod either fails or succeeds . This patch fixed that part
=> Fix Horizontest pod exit

container-images/tcib/base/tobiko/run_tobiko.sh
Similar to debug mode for Tempest, this patch introduces new option for test-operator that keeps the pod running after a successful run or even after a failure has occured. It resolves the issue that oc rsh session is killed once the execution of the run_tobiko.sh file finishes.
=> Add Tobiko debug mode for test-operator

container-images/tcib/base/os/horizontest/run_horizontest.sh
Currently skipping pagination / pagination and filtration test cases in horizon since they are failing due to leftovers from tempest failures . This is being skipped until https://issues.redhat.com/browse/OSPRH-9200 is resolved
=> Modify pytest command to skip pagination tests

container-images/tcib/base/os/tempest/run_tempest.sh
Up until now we were collecting cirros image that is downloaded during the discover-tempest-config phase into the logs folder. The cirros image is not needed artifact and in some edge cases it might happen that the cirros file is too big for it to be stored in the external PV.
This patch removes the cirros image before the logs are collected.
=> [Tempest] Remove cirros image from logs

container-images/tcib/base/os/tempest/run_tempest.sh
Currently users have no idea what tempest packages are installed in the tempest containers. Printing tempest rpms will help the users to know about the same. It will be helpful for debugging in the ci logs.
=> List installed tempest rpms for debugging

container-images/tcib/base/os/tempest/tempest-all/tempest-all.yaml
tempest-all with [1] for downstream case includes
some rpms as weak deps and in order to get those
pulled when available in repos we need to enable
weak deps config which is disabled in base container image.
[1] https://review.rdoproject.org/r/c/openstack/tempest-distgit/+/54169
Related-Issue: [OSPRH-5436](https://issues.redhat.com//browse/OSPRH-5436)
Related-Issue: [OSPRH-6334](https://issues.redhat.com//browse/OSPRH-6334)
=> Enable weak deps for tempest-all container image

container-images/tcib/base/os/tempest/run_tempest.sh
This patch allows to modify IMAGES_CREATION_TIMEOUT for individual images. This better fits the interface of the extraImges parameter in the Tempest CR [1].
[1] https://github.com/openstack-k8s-operators/test-operator/pull/166
=> [Tempest] Modify IMAGES_TIMEOUT for individual images

container-images/tcib/base/os/tempest/run_tempest.sh
Use 'eval' to expand the TEMPESTCONF_OVERRIDES variable prior to using it to run discover-tempest-config. This prevents embedded quotes within the variable from being mangled.
Without the 'eval' embedded quoted strings like "Some String" get mangled into '"Some' 'String"' on the resulting command line.
Jira: [OSPRH-10092](https://issues.redhat.com//browse/OSPRH-10092)
=> [tempest] Handle quotes in TEMPESTCONF_OVERRIDES

container-images/tcib/base/os/tempest/run_tempest.sh
This patch allows to modify IMAGES_CREATION_TIMEOUT for individual images. This better fits the interface of the extraImges parameter in the Tempest CR [1].
[1] https://github.com/openstack-k8s-operators/test-operator/pull/166
=> [18.0.0-proposed][Tempest] Modify IMAGES_TIMEOUT for individual images

container-images/tcib/base/os/tempest/run_tempest.sh
In case there are no results, the xml files get malformed. The malformed xml is then refused by polarion.
This edits the code the way the xml and html results will be generated only in the case when the subunit was generated with 0 return code (successfull operation).
https://issues.redhat.com/browse/OSPRH-9242
=> Avoid malformed results xml

container-images/tcib/base/os/tempest/run_tempest.sh
Fix a regression introduced in PR #210 in which strings with special bash characters need to be escaped: cubswin:) has to be `cubswin:\)`. The need to escape some characters breaks existing CI jobs.
This patch fixes the regression so it's not necessary to escape special characters.
=> [tempest] Fix special chars in TEMPESTCONF_OVERRIDES

container-images/tcib/base/os/horizontest/run_horizontest.sh
Similar to debug mode for Tempest, this patch introduces new option for test-operator that keeps the pod running after a successful run or even after a failure has occurred. It resolves the issue that oc rsh session is killed once the execution of the run_horizontest.sh file finishes.
=> Add Horizontest debug mode for test-operator

container-images/tcib/base/os/ironic-base/ironic-conductor/ironic-conductor.yaml
This will allow the runlogwatch.sh script to switch to using inotifywait instead of polling in a loop.
Jira: [OSPRH-10240](https://issues.redhat.com/browse/OSPRH-10240)
=> Add inotify-tools to ironic-conductor

container-images/tcib/base/os/iscsid/iscsid.yaml
We need socat to be able to run health check for the container.
Related: [OBSDA-574](https://issues.redhat.com/browse/OBSDA-574)
Related: [OSPRH-1052](https://issues.redhat.com/browse/OSPRH-1052)
Closes: [OSPRH-4118](https://issues.redhat.com/browse/OSPRH-4118)
=> Add socat for iscsid

container-images/tcib/base/os/tempest/run_tempest.sh
discover-tempest-config needs 2 flavors it can't run without. When ran without "--create" param, it can't create the flavors itself and fails.
Let's create 2 flavors and delete them afterwards to leave the system intact.
=> Create 2 dummy temporary flavors

container-images/tcib/base/os/ironic-base/ironic-pxe/ironic-pxe.yaml
This is required to refactor the init scripts to accomodate IPA inject CA work. Currently this is done with an ironic-conductor image but it needs to switch to ironic-pxe, and actually this is a more appropriate image to build the ESP image with.
Jira: [OSPRH-4541](https://issues.redhat.com//browse/OSPRH-4541)
=> Add dosfstools, mtools to ironic-pxe

container-images/tcib/base/os/tempest/run_tempest.sh
In addtion to deleting the files with img extension [0] from the logs folder, delete also qcow2 files.
[0] https://github.com/openstack-k8s-operators/tcib/pull/197
=> [Tempest] Remove all images from logs

container-images/containers.yaml, container-images/kolla/base/uid_gid_manage.sh, container-images/tcib/base/openstackclient/openstackclient.yaml, container-images/tcib/base/os/horizon/horizon.yaml, container-images/tcib/base/os/watcher-base/watcher-api/watcher-api.yaml, container-images/tcib/base/os/watcher-base/watcher-applier/watcher-applier.yaml, container-images/tcib/base/os/watcher-base/watcher-base.yaml, container-images/tcib/base/os/watcher-base/watcher-decision-engine/watcher-decision-engine.yaml
This pull request:
* Builds OpenStack Watcher containers
* Add python-watcherclient package to openstackclient container
* Add openstack-watcher-ui package to horizon container
Note: python-watcherclient and openstack-watcher-ui is not available in downstream currently. It is available in CentOS Stream with RDO antelope release. That's why we have added these packages under tcib_distro conditional to avoid breakage downstream.
Test results: https://github.com/openstack-k8s-operators/tcib/pull/215#issuecomment-2459510817 
Jira: https://issues.redhat.com/browse/OSPRH-11085
Co-authored-by: Alfredo Moralejo <amoralej@redhat.com>
Signed-off-by: Chandan Kumar <raukadah@gmail.com>
=> Build openstack-watcher container

container-images/tcib/base/os/tempest/run_tempest.sh
By adding new parameter Expected Failures List in the test operator, we will be able to decide which tests should not have an impact on the job's pass/fail. This patch introduces a way to check if the failing tests are expected to fail and in that case the failing result will be non-voting.
=> Check expected failures based on new parameter

container-images/containers.yaml
Patch enables building the image definition previously introduced in PR 218.
=> Enable the netutils iamge

container-images/tcib/base/os/ironic-base/ironic-inspector/ironic-inspector.yaml
Both ironic-conductor and ironic-inspector have sidecars which cat the ramdisk logs, and these are being converted to use inotifywait.
The conductor image already has the inotify-tools package, this commit adds it to the ironic-inspector image too.
Jira: [OSPRH-10240](https://issues.redhat.com//browse/OSPRH-10240)
=> Add inotify-tools to ironic-inspector image

container-images/tcib/base/os/ironic-base/ironic-conductor/ironic-conductor.yaml
This is required now for iDRAC virtual media boot to be functional, and in the future to enable VNC graphical consoles.
Jira: [OSPRH-11940](https://issues.redhat.com//browse/OSPRH-11940)
=> Add python3-sushy-oem-idrac to ironic-conductor

container-images/tcib/base/ansible-tests/ansibleTests.yaml, container-images/tcib/base/os/horizontest/horizontest.yaml, container-images/tcib/base/os/horizontest/run_horizontest.sh, container-images/tcib/base/os/tempest/tempest-all/tempest-all.yaml, container-images/tcib/base/os/tempest/tempest.yaml, container-images/tcib/base/tobiko/run_tobiko.sh, container-images/tcib/base/tobiko/tobiko.yaml
We want to be able to run test pods spawned by the test-operator with
readOnlyRootFileSystem. This requires mounting of ephemeral storage to
`/var/lib/X` [1]. In this repository all write actions can be performed
(e.g., installation of additional plugins for tempest).
Mounting of the ephemeral storage causes removal of the `run_X.sh` [1]
script and other data that are stored in the `/var/lib/X` directory during
the container build (e.g., tobiko source code directory).  Therefore, we
need to move it to a different location. This patch moves:
-  all the entrypoint scripts for test operator related images
under `/usr/local/bin`.
-  all source code downloaded during the build of a container to
`/usr/local/src`
-  all images downloaded during the build of a container to
`/usr/local/share` …
=> [Test-Operator] Move entrypoint scripts

container-images/tcib/base/tobiko/tobiko.yaml, zuul.d/job.yaml
With recent changes in tobiko 0.8.4, the tobiko pods will download an already customized image instead of using official ubuntu images that were customized during tobiko execution.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2619
=> Remove ubuntu guest image from tobiko

container-images/tcib/base/os/horizontest/run_horizontest.sh
Add required test variables/values which are used as default values for Horizon tests, into horizon.conf
=>  [18.0.-fr1] Add required test variables into horizon.conf

container-images/tcib/base/os/tempest/run_tempest.sh
parallel option is default behavior of tempest and there is no need to specify it.
=> Remove parallel option

container-images/tcib/base/ansible-tests/ansibleTests.yaml
Ansible-test container was missing the sudoers file in it, added a copy statment in the ansibleTest.yaml to add it to the image.
=> Add sudoers file in ansible-test container

zuul.d/job.yaml
The jobs are broken and we probably should not run those tests here.
cherry-picks https://github.com/openstack-k8s-operators/tcib/pull/245
=> [18.0-fr1]Drop tobiko tests from the jobs

container-images/tcib/base/openstackclient/openstackclient.yaml, container-images/tcib/base/os/horizon/horizon.yaml
Watcher related packages are available downstream. This pr removes the centos conditional for the same.
Realted-Jira: https://issues.redhat.com/browse/OSPRH-12829
=> Enable watcher for downstream

container-images/tcib/base/os/glance-api/glance-api.yaml
In preparation to run `Glance` with `httpd+mod_wsgi`, this patch updates the base container image to create in advance `/var/www/cgi-bin/glance` (which will be used as `DocumentRoot`) and copies the `wsgi` script executed by `httpd` through `mod_wsgi` in the target directory.
This change also aligns `glance-api` with `Cinder` and `Manila` base images that already provide the same mechanism.
Related: https://issues.redhat.com/browse/OSPRH-14662
=> Prepare the glance base image to run with httpd+mod_wsgi

container-images/tcib/base/ansible-tests/run_ansible.sh
when using collection inside the ansible-galaxy command with the collection flag only collections are installed this doesn't install additional types of possible requirments like roles. removed the collection keyword from the ansible galaxy install command to allow installing roles as requirements
=> Allow installing not only collection

container-images/tcib/base/os/tempest/tempest-all/tempest-all.yaml
Reverts openstack-k8s-operators/tcib#203
We don't want to enable weak deps as that pulls some unnecessary
packages. And this might not work when moving to do different
container build environment, so reverting. Original tempest-distgit 
patch[1] for which original patch was pushed was also got abandoned.
[1] https://review.rdoproject.org/r/c/openstack/tempest-distgit/+/54169
Related-Issue: [OSPRH-5436](https://issues.redhat.com//browse/OSPRH-5436)
Related-Issue: [OSPRH-6334](https://issues.redhat.com//browse/OSPRH-6334)
=> Revert "Enable weak deps for tempest-all container image"

container-images/tcib/base/os/neutron-base/neutron-server/neutron-server.yaml
This will allow neutron to be configured to use
networking-generic-switch to configure physical switches as an ML2 driver.
This can be merged on the antelope branch when [RELDEL-4625](https://issues.redhat.com//browse/RELDEL-4625) is complete.
Jira: [OSPRH-15368](https://issues.redhat.com//browse/OSPRH-15368)
=> Add python3-networking-generic-switch to neutron-server image

container-images/tcib/base/os/horizontest/run_horizontest.sh
Currently there is no possibility to clone Horizon repository from GitLab because of SSL certificate problem.
=> Set git config http.sslVerify=false

container-images/tcib/base/os/horizon/horizon.yaml, container-images/tcib/base/os/keystone/keystone.yaml, container-images/tcib/base/tobiko/tobiko.yaml
This pr updates the container files for centos stream 10:
-  In CS10, python3.12 is the default python runtime that's why tcib_python_version is used in horizon
-  mod_auth_mellon is dropped from CS10, that's why it is default to cs9 only.
-    tobiko container needs libffi-devel package to be there.
Tested here: https://softwarefactory-project.io/zuul/t/rdoproject.org/build/3137cbfb56cd4445ad1f2805cd1c4e96 and here is the built containers: https://logserver.rdoproject.org/313/rdoproject.org/3137cbfb56cd4445ad1f2805cd1c4e96/ci-framework-data/logs/containers-built.log
Jira: [OSPRH-16308](https://issues.redhat.com//browse/OSPRH-16308)
=> Add CentOS Stream 10 support in tcib

container-images/tcib/base/os/horizontest/horizontest.yaml
Update urllib3 version for it be compatible with Centos10 . With current version there is a conflict 
Resolves https://issues.redhat.com/browse/OSPRH-16481
=> Update urllib version for horizontest container

container-images/tcib/base/base.yaml
In CentOS Stream 10, ca-certificates-2024.2.69_v8.0.303-102.3.el10.noarch package provides /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem file but it does not provides /etc/pki/tls/cert.pem.
In order to cert work properly in EDPM job, we need /etc/pki/tls/cert.pem file otherwise we will see ssl errors.
This pr creates symlink for the same.
Jira: [OSPRH-16670](https://issues.redhat.com//browse/OSPRH-16670)
=> Create symlink for /etc/pki/tls/cert.pem

container-images/tcib/base/os/horizontest/run_horizontest.sh
This commit is excluding federation tests by default as part of extra param because they are only meant to run in the job enabling federation/OIDC support.
=> Exclude federation tests by default

container-images/tcib/base/os/watcher-base/watcher-api/watcher-api.yaml
This is not longer needed after [1].
[1] https://github.com/openstack-k8s-operators/watcher-operator/pull/53
This reverts commit 1ea72804b249cf25ada5c63bcdb5ab8326ee677a.
=> Revert "Add httpd fix to watcher api containerfile"

container-images/tcib/base/base.yaml
In tcib, we use repo-setup provided centos repos. But in centos base image, we have centos and centos-addons repos.
Currently we are hitting repo timeout while pulling content from centos repo due to repo sync issue.
In order to this issue, we are removing centos repo and rely on repo-setup provided centos repos to avoid such  issues.
=> Drop centos repos if exists

container-images/tcib/base/base.yaml
In the past, rhel/centos base containers had default local timezone configured to UTC.
Recently, some base RHEL container images are not providing any default timezone [1], and that's affecting some services, as watcher, which require to discover it.
This patch is setting local timezone to UTC which is the expected one for deployiments using openstack-k8s-operators. I am proposing to provide both TZ environment variable which is used for some libraries and tools [2] but also creating the /etc/localtime file which is the traditional and more extended way of locating the timezone.
[1] https://issues.redhat.com/browse/RHEL-103768
[2] https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html
=> Set UTC timezone in tcib containers

container-images/tcib/base/ansible-tests/ansibleTests.yaml, container-images/tcib/base/os/horizontest/horizontest.yaml, container-images/tcib/base/tobiko/tobiko.yaml
git-core is enough for our usage in these container images, "git" pulls some unnecessary perl deps.
Just noticed while looking into [OSPCIX-935](https://issues.redhat.com//browse/OSPCIX-935)
=> Install git-core instead of git

container-images/tcib/base/os/neutron-base/neutron-server/neutron-server.yaml
This package provides Firewall-As-A-Service service plugin for Neutron. Project neutron-fwaas is in the Neutron stadium in upstream and is revived since couple of cycles. Now we are going to also include it in the RHOSO releases.
Closes: #[OSPRH-15213](https://issues.redhat.com//browse/OSPRH-15213)
=> Add neutron-fwaas package to be installed in Neutron images

container-images/tcib/base/os/horizontest/run_horizontest.sh
Fix for [OSPRH-18853](https://issues.redhat.com//browse/OSPRH-18853)
Change SELENIUM_HEADLESS value to align with new logic: https://review.opendev.org/c/openstack/horizon/+/955932
=> Change SELENIUM_HEADLESS value

container-images/tcib/base/os/tempest/run_tempest.sh
Following Google Style Guide for Bash, I am introducing consistent usage of quotes and brackets wherever possible. Some variables, like `TEMPEST_ARGS` would require special rework in follow-up patch, because of how they are being used currently (not-a-fast-forward change).
[1] https://google.github.io/styleguide/shellguide.html
=> [tempest] Add some brackets+quotes here and there

.github/workflows/toxjobs.yml, .pre-commit-config.yaml, tcib/client/utils.py
Upstream master now supports python 3.10 to python 3.12. The
requirements can't be satisfied for 3.9 anymore, so bump the
tox workflow to 3.12.
With the higher version of python, bumps to flake8 and pylint
were needed as well. Pylint added some new checks it seems. Those
that report errors at the moment are disabled.
One line was exactly 80 character long. I shortened it to pass the
<= 79 character length check.
=> Bump tox tests to python 3.12

tox.ini
So far the antelope branch of tcib project was relying on the same upper constraints as the main branch
– so the one of OpenStack master. However, as OpenStack started to drop support for Python 3.9 we are experiencing more and more compatibility issues. The proper upper-constraints for antelope branch is 2023.1 release.
=> [antelope] Switch to proper upper-constraints

container-images/tcib/base/ansible-tests/run_ansible.sh
Currently, when the AnsibleCollections parameter in test-operator is used to set multiple collections, it throws an error. To fix this issue, the script should not pass all the collections as one full string. This patch fixes that.
=> Fix AnsibleCollections parameter

container-images/tcib/base/ansible-tests/run_ansible.sh
The allows for setting the POD_ANSIBLE_GIT_BRANCH var to specify which branch to check out.
The default behaviour is preserved i.e. clone the repo and use the default branch When the new env var is set, the specified branch is checked out in the cloned repo.
=> [ansibletest] Add a branch for the git repo
